; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

	TITLE	e:\pl_ide\c\cpp_learning\cpp_demo\cppdemo\cppdemo\release\log.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BA@FHKHDKAI@?$FLRiku?5char?5Log?$FN@	; `string'
PUBLIC	??_C@_0L@KHAJPAP@?$FLRiku?5Log?$FN@		; `string'
;	COMDAT ??_C@_0L@KHAJPAP@?$FLRiku?5Log?$FN@
CONST	SEGMENT
??_C@_0L@KHAJPAP@?$FLRiku?5Log?$FN@ DB '[Riku Log]', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@FHKHDKAI@?$FLRiku?5char?5Log?$FN@
CONST	SEGMENT
??_C@_0BA@FHKHDKAI@?$FLRiku?5char?5Log?$FN@ DB '[Riku char Log]', 00H ; `string'
END
