; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

	TITLE	e:\pl_ide\c\cpp_learning\cpp_demo\cppdemo\cppdemo\release\robotstate.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0M@LCNCDMHA@Construct?5?$CD@		; `string'
PUBLIC	??_C@_0L@LICANNJH@Destruct?5?$CD@		; `string'
PUBLIC	?s_counter@RobotState@@0HA			; RobotState::s_counter
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z:PROC
?s_counter@RobotState@@0HA DD 01H DUP (?)		; RobotState::s_counter
_BSS	ENDS
;	COMDAT ??_C@_0L@LICANNJH@Destruct?5?$CD@
CONST	SEGMENT
??_C@_0L@LICANNJH@Destruct?5?$CD@ DB 'Destruct #', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@LCNCDMHA@Construct?5?$CD@
CONST	SEGMENT
??_C@_0M@LCNCDMHA@Construct?5?$CD@ DB 'Construct #', 00H ; `string'
PUBLIC	??1RobotState@@QAE@XZ				; RobotState::~RobotState
PUBLIC	??0RobotState@@QAE@XZ				; RobotState::RobotState
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1RobotState@@QAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
; Function compile flags: /Ogtp
;	COMDAT ??0RobotState@@QAE@XZ
_TEXT	SEGMENT
??0RobotState@@QAE@XZ PROC				; RobotState::RobotState, COMDAT
; _this$ = ecx
; File E:\PL_IDE\C\CPP_learning\Cpp_demo\CppDemo\RobotState.cpp
; Line 9
	mov	edx, DWORD PTR ?s_counter@RobotState@@0HA ; RobotState::s_counter
	push	esi
	mov	esi, ecx
; Line 10
	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	lea	eax, DWORD PTR [edx+1]
	push	edx
	mov	DWORD PTR [esi+48], edx
	mov	edx, OFFSET ??_C@_0M@LCNCDMHA@Construct?5?$CD@
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	mov	DWORD PTR ?s_counter@RobotState@@0HA, eax ; RobotState::s_counter
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
; Line 11
	mov	eax, esi
	pop	esi
	ret	0
??0RobotState@@QAE@XZ ENDP				; RobotState::RobotState
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??1RobotState@@QAE@XZ
_TEXT	SEGMENT
__$EHRec$ = -12						; size = 12
??1RobotState@@QAE@XZ PROC				; RobotState::~RobotState, COMDAT
; _this$ = ecx
; File E:\PL_IDE\C\CPP_learning\Cpp_demo\CppDemo\RobotState.cpp
; Line 14
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1RobotState@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 15
	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	push	DWORD PTR [ecx+48]
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	mov	edx, OFFSET ??_C@_0L@LICANNJH@Destruct?5?$CD@
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
; Line 16
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1RobotState@@QAE@XZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1RobotState@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1RobotState@@QAE@XZ ENDP				; RobotState::~RobotState
END
